---
sidebar: sidebar 
permalink: trident-docker/prereqs-docker.html 
keywords: deploy, astra trident, docker, trident for docker, nfs, iscsi, protcol, nfs protocol, iscsi protocol, configure host, host config 
summary: Trident を導入するには、必要なプロトコルをホストにインストールして設定しておく必要があります。 
---
= 導入の前提条件
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident を導入するには、必要なプロトコルをホストにインストールして設定しておく必要があります。



== 要件を確認します

* の導入がすべてを満たしていることを確認します link:../trident-get-started/requirements.html["要件"]。
* サポートされているバージョンの Docker がインストールされていることを確認します。Docker のバージョンが最新でない場合は、 https://docs.docker.com/engine/install/["インストールまたは更新します"^]。
+
[listing]
----
docker --version
----
* プロトコルの前提条件がホストにインストールされ、設定されていることを確認します。


[cols="3*"]
|===
| プロトコル | オペレーティングシステム | コマンド 


| NFS  a| 
RHEL / CentOS 7.
 a| 
'sudo yum install -y nfs-utils'



| NFS  a| 
Ubuntu
 a| 
'UDO apt-get install-y nfs-common



| iSCSI  a| 
RHEL / CentOS 7.
 a| 
. 次のシステムパッケージをインストールします。
+
'sudo yum install -y lsscsi iscsi-initiator-utils SG3_utils device-mapper-multipath`

. iscsi-initiator-utils のバージョンが 6.2.0.874-2.el7 以降であることを確認します。
+
「 rpm -q iscsi-initiator-utils 」のように入力します

. スキャンを手動に設定：
+
'sudo sed-i'/ ^ \ （ node.session.scan\).*/\1 = manual/ '/etc/iscsi/iscsid.conf

. マルチパスを有効化：
+
'UDO mpathconf--enable --with _multipathd y -- find _multipaths n

+

NOTE: 「 /etc/multipath.conf 」に「 find _ multipaths no 」が「 defVaults 」に含まれていることを確認します。

. 「 iscsid 」と「 multipathd 」が実行されていることを確認します。
+
'sudo systemctl enable -- 現在 iscsid multipathd

. 'iSCSI' を有効にして開始します
+
'sudo systemctl enable -- 現在の iSCSI





| iSCSI  a| 
Ubuntu
 a| 
. 次のシステムパッケージをインストールします。
+
'UDO apt-get install-y open-iscsi lsscsi SG3-utils multipath-tools scsitools'

. open-iscsi バージョンが 2.0.874-5ubuntu2.10 以降（ bionic の場合）または 2.0.874-7.1ubuntu6.1 以降（ Focal の場合）であることを確認します。
+
`d pkg -l open-iscsi`

. スキャンを手動に設定：
+
'sudo sed-i'/ ^ \ （ node.session.scan\).*/\1 = manual/ '/etc/iscsi/iscsid.conf

. マルチパスを有効化：
+
'sudo tee//etc/multipath.conf <-' EOF ' defaults ｛ user_friendy_names yes find _multipaths no ｝ EOF sudo systemctl enable -- 今では multipath-tools.service sudo service multipath-tools restart'

+

NOTE: 「 /etc/multipath.conf 」に「 find _ multipaths no 」が「 defVaults 」に含まれていることを確認します。

. 「 open-iSCSI」 および「マルチパスツール」が有効で実行されていることを確認します。
+
'sudo systemctl status multipath-tools `sudo systemctl enable -- 現在の open-iscsi.service` 'udo systemctl status open-iscsi'



|===