---
sidebar: sidebar 
permalink: trident-docker/stor-config.html 
keywords: deploy, trident, docker, trident for docker, nfs, iscsi, protocol, nfs protocol, iscsi protocol, configure host, host config, storage config, options, variables, ontap, element, storage pool, cvs, cvs-performance, service type, service level, cloud volumes service, cloud volumes 
summary: Astra Trident 構成で使用できる設定オプションを確認してください。 
---
= ストレージ構成オプション
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Astra Trident 構成で使用できる設定オプションを確認してください。



== グローバル構成オプション

以下の設定オプションは、使用するストレージプラットフォームに関係なく、すべての Astra Trident 構成に適用されます。

[cols="3*"]
|===
| オプション | 説明 | 例 


| 「バージョン」  a| 
構成ファイルのバージョン番号
 a| 
`1`



| 'torageDriverName'  a| 
ストレージドライバの名前
 a| 
`ontap-nas`、 `ontap-san`、 `ontap-nas-economy`、
`ontap-nas-flexgroup`、 `solidfire-san`



| 'toragePrefix'  a| 
ボリューム名のオプションのプレフィックス。デフォルト： `netappdvp_`。
 a| 
`staging_`



| 「 limitVolumeSize 」と入力します  a| 
ボリュームサイズに関するオプションの制限。デフォルト：「」（適用されていない）
 a| 
`10g`

|===

TIP: Element バックエンドには 'toragePrefix' （デフォルトを含む）を使用しないでくださいデフォルトでは 'solidfire-san' ドライバはこの設定を無視し ' 接頭辞を使用しませんDocker ボリュームマッピングには特定の tenantID を使用するか、 Docker バージョン、ドライバ情報、名前の munging が使用されている可能性がある場合には Docker から取得した属性データを使用することを推奨します。

作成するすべてのボリュームでデフォルトのオプションを指定しなくても済むようになっています。「 size 」オプションは、すべてのコントローラタイプで使用できます。デフォルトのボリュームサイズの設定方法の例については、 ONTAP の設定に関するセクションを参照してください。

[cols="3*"]
|===
| オプション | 説明 | 例 


| 「 size 」  a| 
新しいボリュームのオプションのデフォルトサイズ。デフォルト： `1G`
 a| 
`10G`

|===


== ONTAP の設定

ONTAP を使用する場合は、上記のグローバル構成値に加えて、次のトップレベルオプションを使用できます。

[cols="3*"]
|===
| オプション | 説明 | 例 


| 「管理 LIF 」  a| 
ONTAP 管理 LIF の IP アドレス。Fully Qualified Domain Name （ FQDN ；完全修飾ドメイン名）を指定できます。
 a| 
`10.0.0.1`



| 「重複排除  a| 
プロトコル LIF の IP アドレス。

* ONTAP NASドライバ*:を指定することをお勧めします `dataLIF`。指定しない場合は、Astra TridentがSVMからデータLIFを取得します。NFSマウント処理に使用するFully Qualified Domain Name（FQDN；完全修飾ドメイン名）を指定して、ラウンドロビンDNSを作成して複数のデータLIF間で負荷を分散することができます。

* ONTAP SANドライバ*: iSCSIには指定しないでくださいAstra Tridentが使用 link:https://docs.netapp.com/us-en/ontap/san-admin/selective-lun-map-concept.html["ONTAP の選択的LUNマップ"^] iSCSI LIFを検出するには、マルチパスセッションを確立する必要があります。の場合は警告が生成されます `dataLIF` は明示的に定義されます。
 a| 
`10.0.0.2`



| 'VM'  a| 
使用する Storage Virtual Machine （管理 LIF がクラスタ LIF である場合は必須）
 a| 
`svm_nfs`



| 「ユーザ名」  a| 
ストレージデバイスに接続するユーザ名
 a| 
`vsadmin`



| 「 password 」と入力します  a| 
ストレージ・デバイスに接続するためのパスワード
 a| 
`secret`



| 「集約」  a| 
プロビジョニング用のアグリゲート（オプション。設定する場合は SVM に割り当てる必要があります）。「 ONTAP-NAS-flexgroup 」ドライバの場合、このオプションは無視されます。SVM に割り当てられたすべてのアグリゲートを使用して FlexGroup ボリュームがプロビジョニングされます。
 a| 
`aggr1`



| 「 AggreglimitateUsage 」と入力します  a| 
オプション。使用率がこの割合を超えている場合は、プロビジョニングを失敗させます
 a| 
`75%`



| 「 nfsvMountOptions 」のように入力します  a| 
NFS マウントオプションのきめ細かな制御。デフォルトは「 -o nfsvers=3 」です。* 「 ONTAP-NAS' 」および「 ONTAP-NAS-エコノミー 」ドライバ専用です。 https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["ここでは、 NFS ホストの設定情報を参照してください"^]。
 a| 
`-o nfsvers=4`



| 「 igroupName 」と入力します  a| 
Astra Tridentはノード単位で作成、管理します `igroups` として `netappdvp`。

この値は変更したり省略したりすることはできません。

*でのみ使用できます `ontap-san` ドライバ*。
 a| 
`netappdvp`



| 「 limitVolumeSize 」と入力します  a| 
最大要求可能ボリュームサイズと qtree 親ボリュームサイズ。* 「 ONTAP-NAS-エコノミー 」ドライバの場合、このオプションにより、作成する FlexVol のサイズも制限されます。 *
 a| 
`300g`



| qtreesPerFlexvol`  a| 
FlexVol あたりの最大 qtree 数は [50 、 300] の範囲で指定する必要があります。デフォルトは 200 です。*「 ONTAP-NAS-エコノミー 」ドライバの場合、このオプションを使用すると、 FlexVol あたりの最大数をカスタマイズできます。
 a| 
`300`

|===
作成するすべてのボリュームでデフォルトのオプションを指定しなくても済むようになっています。

[cols="3*"]
|===
| オプション | 説明 | 例 


| 「平和のための準備」を参照してください  a| 
スペースリザベーションモード `none` （シンプロビジョニング）または `volume` （シック）
 a| 
「 NONE 」



| 「ナプショットポリシー」  a| 
使用するSnapshotポリシー。デフォルトはです `none`
 a| 
「 NONE 」



| 「スナップショット予約」  a| 
Snapshotリザーブの割合。デフォルトはONTAP のデフォルトをそのまま使用する場合はです
 a| 
`10`



| 'plitOnClone  a| 
作成時に親からクローンをスプリットします。デフォルトはです `false`
 a| 
「偽」



| 「暗号化」  a| 
新しいボリュームでNetApp Volume Encryption（NVE）を有効にします。デフォルトは「false」です。このオプションを使用するには、クラスタで NVE のライセンスが設定され、有効になっている必要があります。

NAEがバックエンドで有効になっている場合は、Astra TridentでプロビジョニングされたすべてのボリュームがNAEに有効になります。

詳細については、以下を参照してください。 link:../trident-reco/security-reco.html["Astra TridentとNVEおよびNAEの相互運用性"]。
 a| 
正しいです



| 「 unixPermissions 」  a| 
プロビジョニングされたNFSボリュームのNASオプション。デフォルトはです `777`
 a| 
`777`



| 「スナップショット方向」  a| 
にアクセスするためのNASオプション `.snapshot` ディレクトリ。デフォルトはです `false`
 a| 
「真」



| 「 exportPolicy 」と入力します  a| 
NFSエクスポートポリシーで使用するNASオプション。デフォルトはです `default`
 a| 
`default`



| 'ecurityStyle'  a| 
プロビジョニングされたNFSボリュームにアクセスするためのNASオプション。

NFSのサポート `mixed` および `unix` セキュリティ形式デフォルトはです `unix`。
 a| 
`unix`



| 「 filesystemtype 」です  a| 
ファイルシステムタイプを選択するためのSANオプション。デフォルトはです `ext4`
 a| 
`xfs`



| 階層ポリシー  a| 
使用する階層化ポリシー。デフォルトはです `none`; `snapshot-only` ONTAP 9.5より前のSVM-DR構成の場合
 a| 
「 NONE 」

|===


=== スケーリングオプション

「 ONTAP-NAS' 」ドライバと「 ONTAP-SAN' 」ドライバは、各 Docker ボリューム用の ONTAP FlexVol を作成します。ONTAP では、クラスタノードあたり最大 1 、 000 個の FlexVol がサポートされます。クラスタの最大 FlexVol 数は 12 、 000 です。Docker ボリューム要件がこの制限に適合する場合、「 ONTAP - NAS 」ドライバは FlexVol が提供する Docker ボリューム単位のスナップショットやクローン作成などの追加機能により、 NAS 解決策の方が望ましいとされます。

FlexVol の制限で対応できる容量よりも多くの Docker ボリュームが必要な場合は、「 ONTAP - NAS - エコノミー」または「 ONTAP - SAN - エコノミー」ドライバを選択します。

「 ONTAP - NAS - エコノミー」ドライバは、自動的に管理される FlexVol プール内の ONTAP qtree として Docker ボリュームを作成します。qtree の拡張性は、クラスタノードあたり最大 10 、 000 、クラスタあたり最大 2 、 40 、 000 で、一部の機能を犠牲にすることで大幅に向上しています。「 ONTAP - NAS - エコノミー」ドライバは、 Docker ボリューム単位のスナップショットまたはクローン作成をサポートしていません。


NOTE: Swarm は複数のノード間でのボリューム作成のオーケストレーションを行わないため 'ONTAP-NAS-エコノミー のドライバは現在 Docker Swarm ではサポートされていません

「 ONTAP と SAN の経済性」のドライバは、自動的に管理される FlexVol の共有プール内で、 ONTAP LUN として Docker ボリュームを作成します。この方法により、各 FlexVol が 1 つの LUN に制限されることはなく、 SAN ワークロードのスケーラビリティが向上します。ストレージアレイに応じて、 ONTAP はクラスタあたり最大 16384 個の LUN をサポートします。このドライバは、ボリュームが下位の LUN であるため、 Docker ボリューム単位の Snapshot とクローニングをサポートします。

「 ONTAP-NAS-flexgroup 」ドライバを選択して、数十億個のファイルを含むペタバイト規模に拡張可能な 1 つのボリュームに並列処理を増やすことができます。FlexGroup のユースケースとしては、 AI / ML / DL 、ビッグデータと分析、ソフトウェアのビルド、ストリーミング、ファイルリポジトリなどが考えられます。Trident は、 FlexGroup ボリュームのプロビジョニング時に SVM に割り当てられたすべてのアグリゲートを使用します。Trident での FlexGroup のサポートでは、次の点も考慮する必要があります。

* ONTAP バージョン 9.2 以降が必要です。
* 本ドキュメントの執筆時点では、 FlexGroup は NFS v3 のみをサポートしています。
* SVM で 64 ビットの NFSv3 ID を有効にすることを推奨します。
* 推奨される最小 FlexGroup サイズは 100GB です。
* FlexGroup Volume ではクローニングはサポートされていません。


FlexGroup と FlexGroup に適したワークロードの詳細については、を参照してください https://www.netapp.com/pdf.html?item=/media/12385-tr4571pdf.pdf["『 NetApp FlexGroup Volume Best Practices and Implementation Guide 』にある、ボリュームへの移行に関するセクション"^]。

同じ環境で高度な機能と大規模な拡張性を実現するために 'ONTAP-NAS' を使用して Docker Volume Plugin の複数のインスタンスを実行し ' もう 1 つは「 ONTAP-NAS-エコノミー 」を使用して実行できます



=== ONTAP 構成ファイルの例

*NFS は 'ONTAP-NAS' ドライバの例です

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "defaults": {
      "size": "10G",
      "spaceReserve": "none",
      "exportPolicy": "default"
    }
}
----
*NFS は 'ONTAP-NAS-flexgroup ドライバの例です

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas-flexgroup",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "defaults": {
      "size": "100G",
      "spaceReserve": "none",
      "exportPolicy": "default"
    }
}
----
*NFS は 'ONTAP-NAS-エコノミー 'driver* の例です

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas-economy",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1"
}
----
*iSCSI は 'ONTAP-SAN' ドライバの例です

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-san",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.3",
    "svm": "svm_iscsi",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "igroupName": "netappdvp"
}
----
*NFS は 'ONTAP-SAN-エコノミー ドライバーの例です

[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-san-economy",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.3",
    "svm": "svm_iscsi_eco",
    "username": "vsadmin",
    "password": "password",
    "aggregate": "aggr1",
    "igroupName": "netappdvp"
}
----


== Element ソフトウェアの設定

Element ソフトウェア（ NetApp HCI / SolidFire ）を使用する場合は、グローバルな設定値のほかに、以下のオプションも使用できます。

[cols="3*"]
|===
| オプション | 説明 | 例 


| 「エンドポイント」  a| 
\ https://<login>:<password>@<mvip>/json-rpc/<element-version>
 a| 
\ https://admin:admin@192.168.160.3/json-rpc/8.0



| 「 VIP 」  a| 
iSCSI の IP アドレスとポート
 a| 
10.0.0.7 ： 3260



| 「 tenantname 」  a| 
使用する SolidFire テナント（見つからない場合に作成）
 a| 
`docker`



| 「 InitiatorIFCace 」  a| 
iSCSI トラフィックをデフォルト以外のインターフェイスに制限する場合は、インターフェイスを指定します
 a| 
`default`



| 「タイプ」  a| 
QoS の仕様
 a| 
以下の例を参照してください



| 「 LegacyNamePrefix 」のように入力します  a| 
アップグレードされた Trident インストールのプレフィックス。1.3.2 より前のバージョンの Trident を使用していて、既存のボリュームをアップグレードする場合は、この値を設定して、ボリューム名メソッドを使用してマッピングされた古いボリュームにアクセスする必要があります。
 a| 
`netappdvp-`

|===
「 olidfire -san 」ドライバは Docker Swarm をサポートしていません。



=== Element ソフトウェア構成ファイルの例

[listing]
----
{
    "version": 1,
    "storageDriverName": "solidfire-san",
    "Endpoint": "https://admin:admin@192.168.160.3/json-rpc/8.0",
    "SVIP": "10.0.0.7:3260",
    "TenantName": "docker",
    "InitiatorIFace": "default",
    "Types": [
        {
            "Type": "Bronze",
            "Qos": {
                "minIOPS": 1000,
                "maxIOPS": 2000,
                "burstIOPS": 4000
            }
        },
        {
            "Type": "Silver",
            "Qos": {
                "minIOPS": 4000,
                "maxIOPS": 6000,
                "burstIOPS": 8000
            }
        },
        {
            "Type": "Gold",
            "Qos": {
                "minIOPS": 6000,
                "maxIOPS": 8000,
                "burstIOPS": 10000
            }
        }
    ]
}
----