---
sidebar: sidebar 
permalink: trident-rn.html 
keywords: 'what"s new, new features, enhancements, known issues, resolved issues, troubleshooting' 
summary: ネットアップは、製品やサービスの改善と強化を継続的に行っています。最新バージョンの Astra Trident の機能、拡張機能、バグ修正の一部を以下に示します。 
---
= リリースノート
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


リリースノートでは、最新バージョンの Astra Trident の新機能、拡張機能、およびバグ修正に関する情報を提供しています。


WARNING: インストーラ zip ファイルに含まれている Linux の tridentctl バイナリは ' テスト済みでサポートされているバージョンですzip ファイルの「 /extras 」部分に含まれている「 macos 」バイナリはテストされておらず、サポートされていないことに注意してください。



== 2007年22月の新機能



=== の修正

** Kubernetes **

* HelmまたはTrident OperatorでTridentを設定する際に、ノードセレクタのブール値と数値を処理するように問題 を修正しました。（link:https://github.com/NetApp/trident/issues/700["GitHub問題 #700"^])
* 非CHAPパスのエラーを処理する問題 を修正したため、失敗した場合kubeletが再試行されるようになりました。 link:https://github.com/NetApp/trident/issues/736["GitHub問題 #736"^])




=== 拡張機能

* CSIイメージのデフォルトレジストリとして、k8s .gcr.ioからregistry.k8s .ioに移行します
* ONTAP SANボリュームでは、ノード単位のigroupが使用され、LUNがigroupにマッピングされると同時に、これらのノードにアクティブに公開されてセキュリティ体制が強化されます。Tridentがアクティブなワークロードに影響を与えずに安全であると判断した場合、既存のボリュームは新しいigroupスキームに適宜切り替えられます。
* TridentのインストールにResourceQuotaが含まれ、PriorityClassの消費がデフォルトで制限されたときにTrident DemonSetがスケジュールされるようになりました。
* ANFドライバへのネットワーク機能のサポートが追加されました。（link:https://github.com/NetApp/trident/issues/717["GitHub問題 #717"^])
* ONTAP ドライバにTech Previewの自動MetroCluster スイッチオーバー検出機能を追加。（link:https://github.com/NetApp/trident/issues/228["GitHub問題 #228"^])




=== 非推奨

* **Kubernetes：**サポートされる最小Kubernetes数が1.19に更新されました。
* Astra Data Store（ADS）ドライバをv1beta1 CRDに更新したので、このバージョンのTridentにはADS 22.5.0以降が必要です。
* バックエンド構成では、単一の構成で複数の認証タイプを使用できなくなりました。




=== 削除します

* AWS CVSドライバ（22.04以降で廃止）が削除されました。
* Kubernetes
+
** ノードのポッドから不要なSYS_Admin機能を削除。
** nodeprepを単純なホスト情報とアクティブなサービス検出に減らし、作業者ノードでNFS / iSCSIサービスが利用可能になったことをベストエフォートで確認します。






=== ドキュメント

新しい link:https://docs.netapp.com/us-en/trident/trident-reference/pod-security.html["PODセキュリティ標準"] （PSS）セクションに、インストール時にAstra Tridentによって有効化された権限の詳細が追加されました。



== 2004年10月22日の変更

ネットアップは、製品やサービスの改善と強化を継続的に行っています。Astra Trident の最新機能をいくつかご紹介します。以前のリリースについては、を参照してください https://docs.netapp.com/us-en/trident/earlier-versions.html["以前のバージョンのドキュメント"]。


IMPORTANT: 以前のリリースの Trident からアップグレードして Azure NetApp Files を使用する場合 ' 現在 'location`config パラメータは ' 必須のシングルトンフィールドになっています



=== の修正

* iSCSI イニシエータ名の解析が改善されました。（link:https://github.com/NetApp/trident/issues/681["GitHub問題 #681"^])
* CSI ストレージクラスのパラメータが許可されていない問題 を修正しました。（link:https://github.com/NetApp/trident/issues/598["GitHub問題 #598"^])
* Trident CRD での重複キー宣言が修正されました。（link:https://github.com/NetApp/trident/issues/671["GitHub問題 #671"^])
* 不正確な CSI スナップショットログを修正しました。（link:https://github.com/NetApp/trident/issues/629["GitHub問題 #629"^]）を選択します
* 削除したノードでボリュームを非公開にする問題 を修正しました。（link:https://github.com/NetApp/trident/issues/691["GitHub 問題 #691"^])
* ブロックデバイスでのファイルシステムの不整合の処理が追加されました。（link:https://github.com/NetApp/trident/issues/656["GitHub問題 #656"^])
* インストール時に「 imageRegistry 」フラグを設定するときに、自動サポートイメージをプルする問題 を修正しました。（link:https://github.com/NetApp/trident/issues/715["GitHub問題 #715"^])
* ANF ドライバが複数のエクスポートルールでボリュームのクローニングに失敗した修正済み問題 。




=== 拡張機能

* Trident のセキュアエンドポイントへのインバウンド接続には、 TLS 1.3 以上が必要です。（link:https://github.com/NetApp/trident/issues/698["GitHub問題 #698"^])
* Trident では、セキュアなエンドポイントからの応答に HSTS ヘッダーが追加されました。
* Trident では、 Azure NetApp Files の UNIX 権限機能が自動的に有効化されるようになりました。
* * Kubernetes * ： Trident のデプロイ機能は、システムノードに不可欠な優先度クラスで実行されるようになりました。（link:https://github.com/NetApp/trident/issues/694["GitHub問題 #694"^])




=== 削除します

E シリーズドライバ（ 20.07 以降無効）が削除されました。



== 22.01.1 の変更



=== の修正

* 削除したノードでボリュームを非公開にする問題 を修正しました。（link:https://github.com/NetApp/trident/issues/691["GitHub 問題 #691"])
* ONTAP API 応答でアグリゲートスペースを確保するために nil フィールドにアクセスすると、パニックが修正されました。




== 22.01.0 の変更



=== の修正

* * Kubernetes ：大規模なクラスタのノード登録バックオフ再試行時間を延長します。
* azure-NetApp-files ドライバが、同じ名前の複数のリソースによって混乱することがあるという解決済みの問題 。
* ONTAP SAN IPv6 データ LIF が角かっこで指定した場合に機能するようになりました。
* すでにインポートされているボリュームをインポートしようとすると、 EOF 問題 が返され、 PVC は保留状態になります。（link:https://github.com/NetApp/trident/issues/489["GitHub 問題 #489"])
* Fixed 問題 ： Astra Trident では、 SolidFire ボリュームで作成される Snapshot が 32 個を超えるとパフォーマンスが低下します。
* SSL 証明書の作成時に SHA-1 を SHA-256 に置き換えました。
* リソース名が重複して 1 箇所に操作が制限されるように ANF ドライバを修正しました。
* リソース名が重複して 1 箇所に操作が制限されるように ANF ドライバを修正しました。




=== 拡張機能

* Kubernetes の機能拡張：
+
** Kubernetes 1.23 のサポートが追加されました。
** Trident Operator または Helm 経由でインストールした場合、 Trident ポッドのスケジュールオプションを追加します。（link:https://github.com/NetApp/trident/issues/651["GitHub 問題 #651"^])


* GCP ドライバでリージョン間のボリュームを許可します。（link:https://github.com/NetApp/trident/issues/633["GitHub 問題 #633"^])
* ANF ボリュームでの「 unixPermissions 」オプションのサポートが追加されました。（link:https://github.com/NetApp/trident/issues/666["GitHub 問題 #666"^])




=== 非推奨

Trident REST インターフェイスは、 127.0.0.1 または [::1] アドレスでのみリスンおよびサービスを提供できます



== 21.10.1 の変更点


WARNING: v21.10.0 リリースには、ノードが削除されてから Kubernetes クラスタに再度追加されたときに、 Trident コントローラを CrashLoopBackOff 状態にすることができる問題があります。この問題は、 v21.10.1 (GitHub 問題 669) で修正されています。



=== の修正

* GCP CVS バックエンドでボリュームをインポートする際の競合状態が修正され、インポートに失敗することがありました。
* ノードを削除してから Kubernetes クラスタ（ GitHub 問題 669 ）に再度追加するときに、 Trident コントローラを CrashLoopBackOff 状態にする問題を修正しました。
* SVM 名を指定しなかった場合に問題が検出されないという問題を修正しました（ GitHub 問題 612 ）。




== 21.10.0 の変更点



=== の修正

* XFS ボリュームのクローンをソースボリュームと同じノードにマウントできない固定問題（ GitHub 問題 514 ）
* Astra Trident がシャットダウン時に致命的なエラーを記録した修正版問題（ GitHub 問題 597 ）。
* Kubernetes 関連の修正：
+
** スナップショットを作成するときに 'ONTAP-NAS' および 'ONTAP-NAS-flexgroup ドライバ（ GitHub 問題 645 ）を使用して ' ボリュームの使用済み領域を最小リストアサイズとして返します
** ボリュームのサイズ変更後に 'Failed to expand filesystem エラーがログに記録された問題を修正しました (GitHub 問題 560)
** POD が「 Terminating 」状態で停止する可能性がある固定問題（ GitHub 問題 572 ）。
** 「 ONTAP-SAN-エコノミー 」問題がスナップショット FlexVol （ GitHub 533 ）でいっぱいになる場合があるという問題を修正しました。
** 異なるイメージを持つ固定カスタム YAML インストーラ問題（ GitHub 問題 613 ）。
** Snapshot サイズの計算方法を固定（ GitHub 問題 611 ）。
** 問題は修正され、 Astra Trident のすべてのインストーラが OpenShift としてプレーン Kubernetes を識別できるようになりました（ GitHub 問題 639 ）。
** Kubernetes API サーバにアクセスできない場合に、 Trident オペレータが更新を停止するよう修正しました（ GitHub 問題 599 ）。






=== 拡張機能

* GCP - CVS パフォーマンスボリュームに対する「 unixPermissions 」オプションのサポートが追加されました。
* GCP でのスケール最適化 CVS ボリュームのサポートが 600GiB から 1TiB に追加されました。
* Kubernetes 関連の機能拡張：
+
** Kubernetes 1.22 のサポートが追加されました。
** Trident の operator と Helm チャートを Kubernetes 1.22 （ GitHub 問題 628 ）と連携させるように設定
** tridentctl images コマンドに演算子イメージを追加 (GitHub 問題 570)






=== 実験的な機能強化

* 「 ONTAP SAN 」ドライバでのボリューム・レプリケーションのサポートを追加しました。
* 'ONTAP-NAS-flexgroup 'ONTAP-SAN' および 'ONTAP-NAS-エコノミー ' ドライバの 'tech preview* REST サポートを追加




== 既知の問題

ここでは、本製品の正常な使用を妨げる可能性のある既知の問題について記載します。

* Astra Trident は ' ストレージクラスに fsType が指定されていないボリュームに対して ' ブランクの fsType( `fsType="") を適用するようになりましたKubernetes 1.17 以降を使用する場合、 Trident は NFS ボリュームに空の「 fsType 」を提供できます。iSCSI ボリュームの場合 ' セキュリティコンテキストを使用して fsGroup を実行するときに 'fsType' を StorageClass 上に設定する必要があります
* 複数の Astra Trident インスタンス間でバックエンドを使用する場合、各バックエンド構成ファイルの ONTAP バックエンドに異なる「 toragePrefix 」値を指定するか、 SolidFire バックエンドに異なる「 tenantname 」を使用する必要があります。Astra Trident は、 Astra Trident の他のインスタンスが作成したボリュームを検出できません。ONTAP または SolidFire バックエンドに既存のボリュームを作成しようとすると成功します。 Astra Trident は、ボリューム作成をべき等の操作として扱います。「 toragePrefix 」または「 tenantname 」が異なる場合は、同じバックエンド上に作成されたボリュームに名前の衝突が発生する可能性があります。
* Astra Trident をインストールするときに (tridentctl または Trident Operator を使用 ) 、 tridentctl を使用して Astra Trident を管理するときは、「 KUBECONFIG 」環境変数が設定されていることを確認する必要があります。これは 'tridentctl が機能するべき Kubernetes クラスタを示すために必要です複数の Kubernetes 環境で作業する場合は、「 KBECONFIG 」ファイルが正確にソースされていることを確認する必要があります。
* iSCSI PVS のオンラインスペース再生を実行するには、作業者ノード上の基盤となる OS がボリュームにマウントオプションを渡す必要があります。これは、「 discard 」を必要とする RHEL/RedHat CoreOS インスタンスに当てはまります https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["マウントオプション"^]; discard mountOption がに含まれていることを確認します https://kubernetes.io/docs/concepts/storage/storage-classes/["'torageClass'"^] オンラインブロックの破棄をサポートするため。
* Kubernetes クラスタごとに複数の Astra Trident インスタンスがある場合、 Astra Trident は他のインスタンスと通信できず、作成した他のボリュームを検出できません。そのため、 1 つのクラスタ内で複数のインスタンスを実行している場合、予期しない動作が発生したり、誤ったりすることがあります。Kubernetes クラスタごとに Trident のインスタンスが 1 つだけ必要です。
* Trident がオフラインのときに Astra Trident ベースの「 torageClass 」オブジェクトが Kubernetes から削除された場合、 Astra Trident は、対応するストレージクラスをオンラインに戻ってもデータベースから削除しません。これらのストレージクラスは、「 tridentctl 」または REST API を使用して削除してください。
* 対応する PVC を削除する前に Astra Trident によってプロビジョニングされた PV を削除しても、 Astra Trident は自動的に元のボリュームを削除しません。tridentctl または REST API を使用してボリュームを削除してください。
* FlexGroup では、プロビジョニング要求ごとに一意のアグリゲートセットがないかぎり、同時に複数の ONTAP をプロビジョニングすることはできません。
* IPv6 経由で Astra Trident を使用する場合は、バックエンド定義内の角かっこ内に「 managementlif 」と「 datalif 」を指定する必要があります。例えば、「 [fd20 ： 8b1e ： b258 ： 2000 ： f816 ： 3eff ： feec ： 0]`` 」のようになります。
* OpenShift 4.5 で「 olidfire-san 」ドライバを使用する場合は、基になるワーカーノードが CHAP 認証アルゴリズムとして MD5 を使用していることを確認します。




== 詳細については、こちらをご覧ください

* https://github.com/NetApp/trident["Astra Trident GitHub"^]
* https://netapp.io/persistent-storage-provisioner-for-kubernetes/["Astra Trident のブログ"^]

