---
sidebar: sidebar 
permalink: trident-managing-k8s/uninstall-trident.html 
keywords: uninstall, astra trident, methods, operator, tridentctl, helm, downgrade, obliviate, crds, wipeout, downgrade 
summary: Astra Tridentのアンインストールには、Astra Tridentのインストールと同じ方法を使用する必要があります。アップグレード、依存関係の問題、アップグレードの失敗や不完全な完了後に見つかったバグを修正する必要がある場合は、Astra Tridentをアンインストールし、そのバージョンに固有の手順を使用して以前のバージョンを再インストールする必要があります。 
---
= Astra Trident をアンインストール
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Astra Tridentのアンインストールには、Astra Tridentのインストールと同じ方法を使用する必要があります。


NOTE: アップグレード、依存関係の問題、アップグレードの失敗や不完全な完了後に観察されたバグの修正が必要な場合は、Astra Tridentをアンインストールし、該当する手順を使用して以前のバージョンを再インストールする必要があります。 link:../earlier-versions.html["バージョン"]。これは、以前のバージョンに_downgrade_toを実行するための唯一の推奨方法です。

.作業を開始する前に
Kubernetesクラスタの運用を停止する場合は、Astra Tridentで作成されたボリュームを使用するすべてのアプリケーションをアンインストールする前に削除する必要があります。これにより、PVCが削除される前にKubernetesノードで非公開になります。



== 元のインストール方法を決定する

Astra Tridentは、インストール時と同じ方法でアンインストールする必要があります。アンインストールする前に、Astra Tridentの最初のインストールに使用したバージョンを確認します。

. 使用 `kubectl get pods -n trident` ポッドを検査するために。
+
** オペレータポッドがない場合は、を使用してAstra Tridentがインストールされています `tridentctl`。
** オペレータポッドがある場合、Astra Tridentは手動またはHelmを使用してインストールされています。


. オペレータポッドがある場合は、を使用します `kubectl describe tproc trident` をクリックし、Helmを使用してAstra Tridentがインストールされたかどうかを確認します。
+
** Helmラベルがある場合は、Helmを使用してAstra Tridentがインストールされています。
** Helmラベルがない場合は、Astra TridentをTridentオペレータを使用して手動でインストールしています。






== Tridentオペレータのインストールをアンインストールする

Tridentオペレータのインストールは手動でアンインストールすることも、Helmを使用してアンインストールすることもできます。



=== 手動インストールのアンインストール

Operator を使用して Astra Trident をインストールした場合、次のいずれかの方法で Trident をアンインストールできます。

* **編集 `TridentOrchestrator` アンインストールフラグを設定するには：**を編集できます `TridentOrchestrator` をクリックして設定します `spec.uninstall=true`。
+
** を編集します `TridentOrchestrator` CRおよびを設定します `uninstall` 次のようなフラグを設定します。
+
[listing]
----
kubectl patch torc <trident-orchestrator-name> --type=merge -p '{"spec":{"uninstall":true}}'
----
** uninstall` フラグが 'true' に設定されている場合、 Trident オペレータは Trident をアンインストールしますが、 TridentOrchestrator 自体は削除しません。Trident を再度インストールする場合は、 TridentOrchestrator をクリーンアップして新しい Trident を作成する必要があります。


* **削除 `TridentOrchestrator`:**を削除する `TridentOrchestrator` Astra Tridentの導入に使用したCRでは、Tridentをアンインストールするようオペレータに指示します。
+
** オペレータがの削除を処理します `TridentOrchestrator` さらに、Astra Tridentの導入とデプロイを削除し、インストールの一部として作成したTridentポッドを削除します。
** Astra TridentをアンインストールしてAstra Trident（作成されたCRDを含む）を完全に削除するには、 `TridentOrchestrator` を渡します `wipeout` オプション以降のインストールは新規インストールとして扱われます。
+
[listing]
----
kubectl patch torc <trident-orchestrator-name> --type=merge -p '{"spec":{"wipeout":["crds"],"uninstall":true}}'
----
+

WARNING: この操作は元に戻せません。Astra Tridentを新規にインストールする必要がないかぎり、CRDを完全消去しないでください。たとえば、直前のバージョン以外のバージョンに移動する場合などです。







=== Helmインストールのアンインストール

Helm を使用して Astra Trident をインストールした場合は 'helm uninstall を使用してアンインストールできます

[listing]
----
#List the Helm release corresponding to the Astra Trident install.
helm ls -n trident
NAME          NAMESPACE       REVISION        UPDATED                                 STATUS          CHART                           APP VERSION
trident       trident         1               2021-04-20 00:26:42.417764794 +0000 UTC deployed        trident-operator-21.07.1        21.07.1

#Uninstall Helm release to remove Trident
helm uninstall trident -n trident
release "trident" uninstalled
----


== のアンインストール `tridentctl` インストール

を使用します `uninstall` のコマンド `tridentctl` CRDと関連オブジェクトを除くAstra Tridentに関連付けられているすべてのリソースを削除する。これにより、インストーラを再実行してより新しいバージョンに更新するのが簡単になります。

[listing]
----
./tridentctl uninstall -n <namespace>
----
Astra Trident の完全な削除を実行するには、 Astra Trident によって作成された CRD のフィナライザを削除し、 CRD を削除する必要があります。
