---
sidebar: sidebar 
permalink: trident-managing-k8s/upgrade-operator.html 
keywords: upgrade, trident, methods, operator, tridentctl, helm 
summary: 既存の Astra Trident インストールは、オペレータが簡単にアップグレードできます。 
---
= Trident OperatorまたはHelmを使用してAstra Tridentのインストールをアップグレード
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Astra Tridentは、Tridentオペレータを使用して手動またはHelmを使用してアップグレードできます。Tridentオペレータのインストール環境から別のTridentオペレータのインストール環境へのアップグレード、または `tridentctl` Tridentオペレータバージョンへのインストールレビュー link:upgrade-trident.html#select-an-upgrade-method["アップグレード方法を選択します"] Tridentオペレータのインストールをアップグレードする前に



== 手動インストールのアップグレード

クラスタを対象としたTridentオペレータインストールから、クラスタを対象とした別のTridentオペレータインストールにアップグレードできます。すべてのAstra Tridentバージョン21.01以降では、クラスタを対象とした演算子を使用します。


NOTE: ネームスペースを対象としたオペレータ（バージョン20.07~20.10）を使用してインストールされたAstra Tridentからアップグレードするには、次のアップグレード手順を使用してください： link:../earlier-versions.html["インストールされているバージョン"] 実績があります。

.このタスクについて
Tridentにはバンドルファイルが用意されています。このファイルを使用して、オペレータをインストールしたり、Kubernetesバージョンに対応する関連オブジェクトを作成したりできます。

* クラスタでKubernetes 1.24を実行している場合は、を使用し link:https://github.com/NetApp/trident/tree/stable/v24.06/deploy/bundle_pre_1_25.yaml["Bundle_pre_1_25.yaml"^]ます。
* クラスタでKubernetes 1.25以降を実行している場合は、を使用します link:https://github.com/NetApp/trident/tree/stable/v24.06/deploy/bundle_post_1_25.yaml["bundle_post_1_25.yaml"^]。


.作業を開始する前に
を実行しているKubernetesクラスタを使用していることを確認します link:../trident-get-started/requirements.html["サポートされるKubernetesバージョン"]。

.手順
. Astra Tridentのバージョンを確認します。
+
[listing]
----
./tridentctl -n trident version
----
. 現在の Astra Trident インスタンスのインストールに使用した Trident オペレータを削除たとえば、23.07からアップグレードする場合は、次のコマンドを実行します。
+
[listing]
----
kubectl delete -f 23.07.0/trident-installer/deploy/<bundle.yaml> -n trident
----
. を使用して初期インストールをカスタマイズした場合 `TridentOrchestrator` 属性を編集できます `TridentOrchestrator` インストールパラメータを変更するオブジェクト。これには、ミラーリングされたTridentおよびCSIイメージレジストリをオフラインモードに指定したり、デバッグログを有効にしたり、イメージプルシークレットを指定したりするための変更が含まれます。
. 環境に適したバンドルYAMLファイルを使用してAstra Tridentをインストールします（_YAMLは、または使用している<bundle.yaml>
`bundle_pre_1_25.yaml` `bundle_post_1_25.yaml` のバージョンに基づいています）。たとえば、Astra Trident 24.06をインストールする場合は、次のコマンドを実行します。
+
[listing]
----
kubectl create -f 24.06.0/trident-installer/deploy/<bundle.yaml> -n trident
----




== Helmインストールのアップグレード

Astra Trident Helmのインストールをアップグレードできます。


WARNING: Astra TridentがインストールされているKubernetesクラスタを1.24から1.25以降にアップグレードする場合は、value.yamlを更新して設定する必要があります `excludePodSecurityPolicy` 終了： `true` または、を追加します `--set excludePodSecurityPolicy=true` に移動します `helm upgrade` コマンドを実行してからクラスタをアップグレードしてください。

.手順
. を使用する link:../trident-get-started/kubernetes-deploy-helm.html#deploy-the-trident-operator-and-install-astra-trident-using-helm["Helmを使用したAstra Tridentのインストール"]と、を使用してワンステップでアップグレードできます `helm upgrade trident netapp-trident/trident-operator --version 100.2406.0` 。Helmリポジトリを追加しなかった場合、またはHelmリポジトリを使用してアップグレードできない場合は、次の手順を実行します。
+
.. 次のサイトからAstra Tridentの最新リリースをダウンロードしてください： link:https://github.com/NetApp/trident/releases/latest["GitHubの_Assets_sectionを参照してください"^]。
.. コマンドを使用し `helm upgrade` ます。は、 `trident-operator-24.06.0.tgz` アップグレード先のバージョンを反映しています。
+
[listing]
----
helm upgrade <name> trident-operator-24.06.0.tgz
----
+

NOTE: 初期インストール時にカスタムオプションを設定した場合（TridentイメージとCSIイメージのプライベートなミラーレジストリの指定など）は、 `helm upgrade` コマンド `--set` これらのオプションがupgradeコマンドに含まれるようにするため、それらのオプションの値をdefaultにリセットします。



. を実行します `helm list` グラフとアプリのバージョンが両方ともアップグレードされていることを確認します。を実行します `tridentctl logs` デバッグメッセージを確認します。




== からのアップグレード `tridentctl` Tridentオペレータへのインストール

からTridentの最新リリースにアップグレードできます `tridentctl` インストール：既存のバックエンドとPVCは自動的に使用可能になります。


NOTE: インストール方法を切り替える前に、 link:../trident-get-started/kubernetes-deploy.html#moving-between-installation-methods["インストール方法を切り替える"]。

.手順
. 最新の Astra Trident リリースをダウンロード
+
[listing]
----
# Download the release required [24.060.0]
mkdir 24.06.0
cd 24.06.0
wget https://github.com/NetApp/trident/releases/download/v24.06.0/trident-installer-24.06.0.tar.gz
tar -xf trident-installer-24.06.0.tar.gz
cd trident-installer
----
. マニフェストから「 tridentオーケストラ 」 CRD を作成します。
+
[listing]
----
kubectl create -f deploy/crds/trident.netapp.io_tridentorchestrators_crd_post1.16.yaml
----
. クラスタを対象としたオペレータを同じネームスペースに導入します。
+
[listing]
----
kubectl create -f deploy/<bundle-name.yaml>

serviceaccount/trident-operator created
clusterrole.rbac.authorization.k8s.io/trident-operator created
clusterrolebinding.rbac.authorization.k8s.io/trident-operator created
deployment.apps/trident-operator created
podsecuritypolicy.policy/tridentoperatorpods created

#Examine the pods in the Trident namespace
NAME                                  READY   STATUS    RESTARTS   AGE
trident-controller-79df798bdc-m79dc   6/6     Running   0          150d
trident-node-linux-xrst8              2/2     Running   0          150d
trident-operator-5574dbbc68-nthjv     1/1     Running   0          1m30s
----
. Astra Trident をインストールするための TridentOrchestrator CR を作成します。
+
[listing]
----
cat deploy/crds/tridentorchestrator_cr.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident

kubectl create -f deploy/crds/tridentorchestrator_cr.yaml

#Examine the pods in the Trident namespace
NAME                                READY   STATUS    RESTARTS   AGE
trident-csi-79df798bdc-m79dc        6/6     Running   0          1m
trident-csi-xrst8                   2/2     Running   0          1m
trident-operator-5574dbbc68-nthjv   1/1     Running   0          5m41s
----
. Tridentが目的のバージョンにアップグレードされたことを確認
+
[listing]
----
kubectl describe torc trident | grep Message -A 3

Message:                Trident installed
Namespace:              trident
Status:                 Installed
Version:                v24.06.0
----

