---
sidebar: sidebar 
permalink: trident-use/backend_ops_tridentctl.html 
keywords: backends, storage system, anf, cvs for aws, cvs for gcp, element, hci, solidfire, ontap, aff, fas, ontap select, configure backends, tridentctl, create backends, delete backends, view backends, update backends 
summary: tridentctl を使用してバックエンド管理操作を実行する方法について説明します 
---
= tridentctl を使用してバックエンド管理を実行します
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


tridentctl を使用してバックエンド管理操作を実行する方法について説明します



== バックエンドを作成します

を作成したら link:backends.html["バックエンド構成ファイル"^]を使用して、次のコマンドを実行します。

[listing]
----
$ tridentctl create backend -f <backend-file> -n trident
----
バックエンドの作成に失敗した場合は、バックエンドの設定に何か問題があります。次のコマンドを実行すると、ログを表示して原因を特定できます。

[listing]
----
$ tridentctl logs -n trident
----
構成ファイルの問題を特定して修正したら ' 再度 create コマンドを実行します



== バックエンドを削除します

Astra Trident からバックエンドを削除するには、次の手順を実行します。

. バックエンド名を取得します。
+
[listing]
----
$ tridentctl get backend -n trident
----
. バックエンドを削除します。
+
[listing]
----
$ tridentctl delete backend <backend-name> -n trident
----



NOTE: Astra Trident で、まだ存在しているこのバックエンドからボリュームとスナップショットをプロビジョニングしている場合、バックエンドを削除すると、新しいボリュームをプロビジョニングできなくなります。バックエンドは「削除」状態のままになり、 Trident は削除されるまでそれらのボリュームとスナップショットを管理し続けます。



== 既存のバックエンドを表示します

Trident が認識しているバックエンドを表示するには、次の手順を実行します。

* 概要を取得するには、次のコマンドを実行します。
+
[listing]
----
$ tridentctl get backend -n trident
----
* すべての詳細を確認するには、次のコマンドを実行します。
+
[listing]
----
$ tridentctl get backend -o json -n trident
----




== バックエンドを更新します

新しいバックエンド構成ファイルを作成したら、次のコマンドを実行します。

[listing]
----
$ tridentctl update backend <backend-name> -f <backend-file> -n trident
----
バックエンドの更新が失敗した場合、バックエンドの設定に問題があるか、無効な更新を試行しました。次のコマンドを実行すると、ログを表示して原因を特定できます。

[listing]
----
$ tridentctl logs -n trident
----
構成ファイルの問題を特定して修正したら 'update コマンドを再度実行できます



== バックエンドを使用するストレージクラスを特定します

ここでは ' バックエンド・オブジェクトの tridentctl 出力と同じ JSON を使用して回答で実行できる質問の例を示しますこれには 'jq' ユーティリティが使用されますこのユーティリティをインストールする必要があります

[listing]
----
$ tridentctl get backend -o json | jq '[.items[] | {backend: .name, storageClasses: [.storage[].storageClasses]|unique}]'
----
これは、「 TridentBackendConfig 」を使用して作成されたバックエンドにも適用されます。
