---
sidebar: sidebar 
permalink: trident-use/manage-stor-class.html 
keywords: storage class, manage storage class, storage classes, kubernetes storage classes 
summary: 既存のストレージクラスを表示したり、デフォルトのストレージクラスを設定したり、ストレージクラスバックエンドを識別したり、ストレージクラスを削除したりできます。 
---
= ストレージクラスを管理する
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
既存のストレージクラスを表示したり、デフォルトのストレージクラスを設定したり、ストレージクラスバックエンドを識別したり、ストレージクラスを削除したりできます。



== 既存のストレージクラスを表示します

* 既存の Kubernetes ストレージクラスを表示するには、次のコマンドを実行します。


[listing]
----
kubectl get storageclass
----
* Kubernetes ストレージクラスの詳細を表示するには、次のコマンドを実行します。


[listing]
----
kubectl get storageclass <storage-class> -o json
----
* Astra Trident の同期されたストレージクラスを表示するには、次のコマンドを実行します。


[listing]
----
tridentctl get storageclass
----
* Astra Trident の同期されたストレージクラスの詳細を表示するには、次のコマンドを実行します。


[listing]
----
tridentctl get storageclass <storage-class> -o json
----


== デフォルトのストレージクラスを設定する

Kubernetes 1.6 では、デフォルトのストレージクラスを設定する機能が追加されています。永続ボリューム要求（ PVC ）に永続ボリュームが指定されていない場合に、永続ボリュームのプロビジョニングに使用するストレージクラスです。

* ストレージクラスの定義でアノテーションの「 torageclass.Kubernetes .io/is-default-class 」を true に設定して、デフォルトのストレージクラスを定義します。仕様に応じて、それ以外の値やアノテーションがない場合は false と解釈されます。
* 次のコマンドを使用して、既存のストレージクラスをデフォルトのストレージクラスとして設定できます。


[listing]
----
kubectl patch storageclass <storage-class-name> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
----
* 同様に、次のコマンドを使用して、デフォルトのストレージクラスアノテーションを削除できます。


[listing]
----
kubectl patch storageclass <storage-class-name> -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
----
また、このアノテーションが含まれている Trident インストーラバンドルにも例があります。


NOTE: クラスタ内のデフォルトのストレージクラスは一度に1つだけにしてください。Kubernetes では、技術的に複数のストレージを使用することはできますが、デフォルトのストレージクラスがまったくない場合と同様に動作します。



== ストレージクラスのバックエンドを特定します

これは 'tridentctl が 'Astra Trident バックエンド・オブジェクトに出力する JSON を使用して回答が実行できる質問の一例ですこれには 'jq' ユーティリティが使用されますこのユーティリティを最初にインストールする必要があります

[listing]
----
tridentctl get storageclass -o json | jq  '[.items[] | {storageClass: .Config.name, backends: [.storage]|unique}]'
----


== ストレージクラスを削除する

Kubernetes からストレージクラスを削除するには、次のコマンドを実行します。

[listing]
----
kubectl delete storageclass <storage-class>
----
「 <storage-class> 」は、ご使用のストレージクラスに置き換えてください。

このストレージクラスで作成された永続ボリュームには変更はなく、 Astra Trident によって引き続き管理されます。


NOTE: Astra Tridentでは空白が強制される `fsType` を作成します。iSCSIバックエンドの場合は、適用することを推奨します `parameters.fsType` ストレージクラス。既存のストレージクラスを削除して、で再作成する必要があります `parameters.fsType` 指定された。
