---
sidebar: sidebar 
permalink: trident-use/ontap-san.html 
keywords: trident backend, ontap san, ontap-san, ontap-san-economy, fsx, drivers, access modes, rwo, rwx, rwp, rwop, file system 
summary: ONTAP SAN ドライバを使用して ONTAP バックエンドを設定する方法について説明します。 
---
= ONTAP SANドライバの概要
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP および Cloud Volumes ONTAP SAN ドライバを使用した ONTAP バックエンドの設定について説明します。



== ONTAP SANドライバの詳細

Astra Tridentは、ONTAPクラスタと通信するための次のSANストレージドライバを提供します。サポートされているアクセスモードは、_ReadWriteOnce_(RWO)、_ReadOnlyMany_(ROX)、_ReadWriteMany_(RWX)、_ReadWriteOncePod_(RWOP)です。


IMPORTANT: 保護、リカバリ、モビリティにAstra Controlを使用している場合は、 <<Astra Controlドライバの互換性>>。

[cols="2, 1, 1, 2, 2"]
|===
| ドライバ | プロトコル | ボリュームモード | サポートされているアクセスモード | サポートされるファイルシステム 


| 「 ontap - san 」  a| 
iSCSI
 a| 
ブロック
 a| 
RWO、ROX、RWX、RWOP
 a| 
ファイルシステムなし。rawブロックデバイスです



| 「 ontap - san 」  a| 
iSCSI
 a| 
ファイルシステム
 a| 
RWO、RWOP

ROXおよびRWXは、ファイルシステムボリュームモードでは使用できません。
 a| 
「 xfs 」、「 ext3 」、「 ext4 」



| 「 ontap - san 」  a| 
NVMe/FC

を参照してください <<NVMe/TCPに関するその他の考慮事項>>。
 a| 
ブロック
 a| 
RWO、ROX、RWX、RWOP
 a| 
ファイルシステムなし。rawブロックデバイスです



| 「 ontap - san 」  a| 
NVMe/FC

を参照してください <<NVMe/TCPに関するその他の考慮事項>>。
 a| 
ファイルシステム
 a| 
RWO、RWOP

ROXおよびRWXは、ファイルシステムボリュームモードでは使用できません。
 a| 
「 xfs 」、「 ext3 」、「 ext4 」



| 「 ONTAP - SAN - エコノミー」  a| 
iSCSI
 a| 
ブロック
 a| 
RWO、ROX、RWX、RWOP
 a| 
ファイルシステムなし。rawブロックデバイスです



| 「 ONTAP - SAN - エコノミー」  a| 
iSCSI
 a| 
ファイルシステム
 a| 
RWO、RWOP

ROXおよびRWXは、ファイルシステムボリュームモードでは使用できません。
 a| 
「 xfs 」、「 ext3 」、「 ext4 」

|===


=== Astra Controlドライバの互換性

Astra Controlは、で作成したボリュームに対して、シームレスな保護、ディザスタリカバリ、および移動（Kubernetesクラスタ間でボリュームを移動）を提供します `ontap-nas`、 `ontap-nas-flexgroup`および `ontap-san` ドライバ。を参照してください link:https://docs.netapp.com/us-en/astra-control-center/use/replicate_snapmirror.html#replication-prerequisites["Astra Controlレプリケーションの前提条件"^] を参照してください。

[WARNING]
====
* 使用 `ontap-san-economy` 永続的ボリュームの使用数が次の値よりも多いと予想される場合のみ link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["サポートされるONTAPの制限"^]。
* 使用 `ontap-nas-economy` 永続的ボリュームの使用数が次の値よりも多いと予想される場合のみ link:https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html["サポートされるONTAPの制限"^] および `ontap-san-economy` ドライバは使用できません。
* 使用しないでください `ontap-nas-economy` データ保護、ディザスタリカバリ、モビリティのニーズが予想される場合。


====


== ユーザ権限

Astra Trident は、 ONTAP 管理者または SVM 管理者のいずれかとして実行されることを想定しています。通常は、「 admin 」クラスタユーザまたは「 vsadmin 」 SVM ユーザを使用するか、同じロールを持つ別の名前のユーザを使用します。Amazon FSX for NetApp ONTAP 環境では、 Astra Trident は、 ONTAP 管理者または SVM 管理者として、クラスタ「 fsxadmin 」ユーザまたは「 vsadmin 」 SVM ユーザ、または同じロールを持つ別の名前のユーザを実行する必要があります。「 fsxadmin 」ユーザは、クラスタ管理ユーザの限定的な代替ユーザです。


NOTE: limitAggregateUsage パラメータを使用する場合は、クラスタ管理者権限が必要です。Amazon FSX for NetApp ONTAP を Astra Trident とともに使用する場合、「 limitAggregateUsage 」パラメータは「 vsadmin 」および「 fsxadmin 」ユーザアカウントでは機能しません。このパラメータを指定すると設定処理は失敗します。

ONTAP内でTridentドライバが使用できる、より制限の厳しいロールを作成することは可能ですが、推奨しません。Trident の新リリースでは、多くの場合、考慮すべき API が追加で必要になるため、アップグレードが難しく、エラーも起こりやすくなります。



== NVMe/TCPに関するその他の考慮事項

Astra Tridentでは、 `ontap-san` 以下を含むドライバー：

* IPv6
* NVMeボリュームのSnapshotとクローン
* NVMeボリュームのサイズ変更
* Astra Tridentでライフサイクルを管理できるように、Astra Tridentの外部で作成されたNVMeボリュームをインポートする
* NVMeネイティブマルチパス
* Kubernetesノードのグレースフルシャットダウンまたはグレースフルシャットダウン（24.02）


Astra Tridentでは次の機能がサポートされません。

* NVMeでネイティブにサポートされるDH-HMAC-CHAP
* Device Mapper（DM；デバイスマッパー）マルチパス
* LUKS暗号化

