---
sidebar: sidebar 
permalink: trident-use/vol-provision.html 
keywords: volumes, pvc, pv, persistentvolume, persistentvolumeclaim, mount, pod, provision 
summary: 設定したKubernetes StorageClassを使用してPVへのアクセスを要求するPersistentVolume（PV）とPersistentVolumeClaim（PVC）を作成します。その後、PVをポッドにマウントできます。 
---
= ボリュームをプロビジョニングする
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
設定したKubernetes StorageClassを使用してPVへのアクセスを要求するPersistentVolume（PV）とPersistentVolumeClaim（PVC）を作成します。その後、PVをポッドにマウントできます。



== 概要

A link:https://kubernetes.io/docs/concepts/storage/persistent-volumes/["永続ボリューム_"^] （PV）は、Kubernetesクラスタ上のクラスタ管理者がプロビジョニングする物理ストレージリソースです。。 https://kubernetes.io/docs/concepts/storage/persistent-volumes["PersistentVolumeClaim_"^] （PVC）は、クラスタ上のPersistentVolumeへのアクセス要求です。

PVCは、特定のサイズまたはアクセスモードのストレージを要求するように設定できます。クラスタ管理者は、関連付けられているStorageClassを使用して、PersistentVolumeのサイズとアクセスモード（パフォーマンスやサービスレベルなど）以上を制御できます。

PVとPVCを作成したら、ポッドにボリュームをマウントできます。



=== マニフェストの例

.PersistentVolumeサンプルマニフェスト
[%collapsible]
====
このサンプルマニフェストは、StorageClassに関連付けられた10Giの基本PVを示しています。 `basic-csi`。

[listing]
----
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-storage
  labels:
    type: local
spec:
  storageClassName: basic-csi
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/my/host/path"
----
====
.PersistentVolumeClaimサンプルマニフェスト
[%collapsible]
====
次に、基本的なPVC設定オプションの例を示します。

.RWOアクセスを備えたPVC
次の例は、という名前のStorageClassに関連付けられた、RWOアクセスが設定された基本的なPVCを示しています。 `basic-csi`。

[listing]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-csi
----
.NVMe / TCP対応PVC
この例は、という名前のStorageClassに関連付けられたNVMe/TCPの基本的なPVCとRWOアクセスを示しています。 `protection-gold`。

[listing]
----
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
name: pvc-san-nvme
spec:
accessModes:
  - ReadWriteOnce
resources:
  requests:
    storage: 300Mi
storageClassName: protection-gold
----
====
.PODマニフェストのサンプル
[%collapsible]
====
次の例は、PVCをポッドに接続するための基本的な設定を示しています。

.キホンセツテイ
[listing]
----
kind: Pod
apiVersion: v1
metadata:
  name: pv-pod
spec:
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
       claimName: basic
  containers:
    - name: pv-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/my/mount/path"
          name: pv-storage
----
.NVMe/TCPの基本構成
[listing]
----
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
    - image: nginx
      name: nginx
      resources: {}
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: task-pv-storage
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
      claimName: pvc-san-nvme
----
====


== PVおよびPVCの作成

.手順
. PVを作成します。
+
[listing]
----
kubectl create -f pv.yaml
----
. PVステータスを確認します。
+
[listing]
----
kubectl get pv
NAME        CAPACITY  ACCESS MODES  RECLAIM POLICY  STATUS    CLAIM  STORAGECLASS  REASON  AGE
pv-storage  4Gi       RWO           Retain          Available                              7s
----
. PVC を作成します。
+
[listing]
----
kubectl create -f pvc.yaml
----
. PVCステータスを確認します。
+
[listing]
----
kubectl get pvc
NAME        STATUS VOLUME     CAPACITY ACCESS MODES STORAGECLASS AGE
pvc-storage Bound  pv-name 2Gi      RWO                       5m
----
. ボリュームをポッドにマウントします。
+
[listing]
----
kubectl create -f pv-pod.yaml
----
+

NOTE: 進捗状況は次を使用して監視できます。 `kubectl get pod --watch`。

. ボリュームがマウントされていることを確認します。 `/my/mount/path`。
+
[listing]
----
kubectl exec -it task-pv-pod -- df -h /my/mount/path
----
. ポッドを削除できるようになりました。Podアプリケーションは存在しなくなりますが、ボリュームは残ります。
+
[listing]
----
kubectl delete pod task-pv-pod
----


を参照してください link:../trident-reference/objects.html["Kubernetes オブジェクトと Trident オブジェクト"] ストレージクラスとの連携の詳細については、を参照してください。 `PersistentVolumeClaim` とパラメータを使用して、Astra Tridentでボリュームをプロビジョニングする方法を制御します。
