---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-customize-deploy-tridentctl.html 
keywords: deploy, astra trident, methods, operator, tridentctl, helm, attributes, customize, tridentorchestrator 
summary: Trident のインストーラでは、属性をカスタマイズできます。 
---
= tridentctl 展開をカスタマイズします
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Trident インストーラを使用して属性をカスタマイズできます。たとえば、 Trident イメージをプライベートリポジトリにコピーした場合、 -trident-image' を使用してイメージ名を指定できます。Trident イメージと必要な CSI サイドカーイメージをプライベートリポジトリにコピーした場合は、 --image_registry' スイッチを使用してリポジトリの場所を指定することをお勧めします。この場合、形式は「 <registry fqdn>[:port] 」です。

Astra Trident が自動的にワーカーノードを構成するには、「 --enable-node-prep 」を使用します。この機能の詳細については、を参照してください link:../trident-use/automatic-workernode.html["こちらをご覧ください"^]。


NOTE: ワーカーノードの自動準備は * ベータ機能 * で、非本番環境でのみ使用できます。

通常の「 /var/lib/kubelet 」以外のパスに「 kubelet 」がデータを保持している Kubernetes の配布を使用する場合は、「 --kubelet -dir 」を使用して代替パスを指定できます。

インストーラの引数で許可される範囲を超えてインストールをカスタマイズする必要がある場合は、配置ファイルをカスタマイズすることもできます。--generate-custom-yaml パラメータを使用して、インストーラの「 etup 」ディレクトリに次の YAML ファイルを作成します。

* trident-clusterrolebinding.yaml
* trident-deployment.yaml
* trident-CRDs .YAML
* trident-clusterrolment.yaml
* trident-demimonimon.yamml`
* trident-service.yaml
* trident-namespac.yaml
* trident-ServiceAccount.yaml


これらのファイルを生成したら、必要に応じて変更し、「 --use-custom-yaml 」を使用してカスタム展開をインストールできます。

[listing]
----
./tridentctl install -n trident --use-custom-yaml
----