---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-customize-deploy.html 
keywords: deploy, trident, methods, operator, tridentctl, helm, attributes, customize, tridentorchestrator, smb, windows 
summary: 'Trident オペレータは "TridentOrchestrator 仕様の属性を使用して "Astra Trident のインストール方法をカスタマイズできます' 
---
= Trident オペレータの環境をカスタマイズ
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Tridentオペレータは、の属性を使用してAstra Tridentのインストールをカスタマイズできます `TridentOrchestrator` 仕様

インストールをカスタマイズする場合は、それ以上のカスタマイズが必要です `TridentOrchestrator` arguments allow、の使用を検討する必要があります `tridentctl` 必要に応じて変更できるカスタムYAMLマニフェストを生成します。


WARNING: `spec.namespace` は、で指定します `TridentOrchestrator` Astra Tridentがインストールされているネームスペースを示します。このパラメータ * は、 Astra Trident のインストール後に更新できません * 。これを実行すると、が実行されます `TridentOrchestrator` ステータスをに変更します `Failed`。Astra Tridentは、ネームスペース間での移行を意図していません。



== 設定オプション

このテーブルの詳細 `TridentOrchestrator` 属性：

[cols="3"]
|===
| パラメータ | 説明 | デフォルト 


| 「 namespace 」を参照してください | Astra Trident をインストールするネームスペース | デフォルト 


| 「バグ」 | Astra Trident のデバッグを有効にします | いいえ 


| `windows` | をに設定します `true` Windowsワーカーノードへのインストールを有効にします。 | いいえ 


| 「 IPv6 」 | IPv6 経由の Astra Trident をインストール | いいえ 


| k8sTimeout | Kubernetes 処理のタイムアウト | 30 秒 


| 'ilenceAutosupport | AutoSupport バンドルをネットアップに自動的に送信しない | いいえ 


| enableNodePrep | ワーカーノードの依存関係を自動的に管理（ * beta * ） | いいえ 


| 「 autosupportImage 」を参照してください | AutoSupport テレメトリのコンテナイメージ | 「NetApp/trident-autosupport：22.10.0」 


| 「 autosupportProxy 」と入力します | AutoSupport テレメトリを送信するプロキシのアドレス / ポート | "http://proxy.example.com:8888"[] 


| uninstall | Astra Trident のアンインストールに使用するフラグ | いいえ 


| 「 logFormat 」 | Astra Trident のログ形式が使用 [text 、 JSON] | テキスト（ Text ） 


| 「 tridentImage 」のように入力します | インストールする Astra Trident イメージ | 「 NetApp / Trident ： 21.04 」 


| 「 imageRegistry 」と入力します | 内部レジストリへのパス。形式は「 <registry fqdn>[:port][/ssubpath]] 」です | "k83.gcr.io/sig-storage (k8s 1.19+)またはQua.io/k8scsi" 


| 「 kubeletDir 」を参照してください | ホスト上の kubelet ディレクトリへのパス | 「 /var/lib/kubelet 」 


| 「 wippeout 」 | Astra Trident を完全に削除するために削除するリソースのリスト |  


| 「 imagePullSecrets 」 | 内部レジストリからイメージをプルするシークレット |  


| controller'PluginNodeSelector | Trident Controller CSI プラグインを実行しているポッドの追加ノードセレクタ。pod.spec.nodeSelector と同じ形式を使用します。 | デフォルトはありません。オプションです 


| controllerPluginTolerations | Trident Controller CSI プラグインを実行しているポッドに対する許容値を上書きします。POD .spec.Toleratations と同じ形式を使用します。 | デフォルトはありません。オプションです 


| 「 nodePluginNodeSelector 」 | Trident ノード CSI プラグインを実行しているポッドの追加ノードセレクタ。pod.spec.nodeSelector と同じ形式を使用します。 | デフォルトはありません。オプションです 


| 「 nodePluginTolerations` 」 | Trident Node CSI プラグインを実行しているポッドに対する許容値を上書きします。POD .spec.Toleratations と同じ形式を使用します。 | デフォルトはありません。オプションです 
|===

NOTE: ポッドパラメータの書式設定の詳細については、を参照してください link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["ポッドをノードに割り当てます"^]。



== 構成例

上記の属性は、を定義するときに使用できます `TridentOrchestrator` をクリックして、インストールをカスタマイズします。

.例1：基本的なカスタム構成
====
次に、基本的なカスタム構成の例を示します。

[listing]
----
cat deploy/crds/tridentorchestrator_cr_imagepullsecrets.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  imagePullSecrets:
  - thisisasecret
----
====
.例2：ノードセレクタを使用して導入します
====
次の例では、ノードセレクタを使用してTridentを導入する方法を示します。

[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  controllerPluginNodeSelector:
    nodetype: master
  nodePluginNodeSelector:
    storage: netapp
----
====
.例3：Windowsワーカーノードに導入する
====
この例は、Windowsワーカーノードへの導入を示しています。

[listing]
----
$ cat deploy/crds/tridentorchestrator_cr.yaml
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  namespace: trident
  windows: true
----
====