---
sidebar: sidebar 
permalink: trident-concepts/intro.html 
keywords: product overview, astra trident, fsx, element, astra, google cloud, cvs 
summary: Astra Trident は、ネットアップが Astra 製品ファミリーの一部として管理している、完全にサポートされているオープンソースプロジェクトです。Container Storage Interface （ CSI ）などの業界標準のインターフェイスを使用して、コンテナ化されたアプリケーションの永続性に対する要求を満たすことができるように設計されています。 
---
= Astra Trident の概要
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Astra Trident は、ネットアップがの一部として管理している、完全にサポートされているオープンソースプロジェクトです link:https://docs.netapp.com/us-en/astra-family/intro-family.html["Astra 製品ファミリー"^]。Container Storage Interface （ CSI ）などの業界標準のインターフェイスを使用して、コンテナ化されたアプリケーションの永続性に対する要求を満たすことができるように設計されています。

Kubernetes クラスタにポッドとして Trident を導入し、 Kubernetes ワークロードに動的なストレージオーケストレーションサービスを提供コンテナ化されたアプリケーションは、 ONTAP （ AFF / FAS / Select / Cloud / Amazon FSX for NetApp ONTAP ）、 Element ソフトウェア（ NetApp HCI / SolidFire ）、 Astra データストア、 Azure NetApp Files サービス、 Google Cloud 上の Cloud Volumes Service など、ネットアップの幅広いポートフォリオの永続的ストレージをすばやく簡単に消費できます。

Astra Trident は、 NetApp の Astra の基盤テクノロジでもあり、 NetApp のスナップショット、バックアップ、レプリケーション、クローニングに業界をリードするデータ管理テクノロジを活用して、 Kubernetes ワークロードのデータ保護、ディザスタリカバリ、ポータビリティ、移行のユースケースに対応します。



== サポートされる Kubernetes クラスタアーキテクチャ

Astra Trident は、次の Kubernetes アーキテクチャでサポートされています。

[cols="3*"]
|===
| Kubernetes クラスタアーキテクチャ | サポートされます | デフォルトのインストールです 


| 単一マスター、コンピューティング | はい。  a| 
はい。



| 複数のマスター、コンピューティング | はい。  a| 
はい。



| マスター、「 etcd' 」、コンピューティング | はい。  a| 
はい。



| マスター、インフラ、コンピューティング | はい。  a| 
はい。

|===


== アストラとは

Astra を使用すると、 Kubernetes で実行されている大量のデータコンテナ化ワークロードを、パブリッククラウドとオンプレミスの間で簡単に管理、保護、移動できます。Astra は、ネットアップの実績ある拡張可能なパブリッククラウドストレージポートフォリオとオンプレミスのストレージポートフォリオから、 Astra Trident を使用して永続的なコンテナストレージをプロビジョニングし、提供します。また、 Kubernetes ワークロード向けに、 Snapshot 、バックアップとリストア、アクティビティログ、アクティブクローニングによるデータ保護、ディザスタ / データリカバリ、データ監査、移行のユースケースなど、アプリケーションに対応した高度なデータ管理機能も豊富に用意されています。

Astra のページで無料トライアルに登録できます。



== を参照してください。

* https://docs.netapp.com/us-en/astra-family/intro-family.html["ネットアップアストラ製品ファミリー"]
* https://docs.netapp.com/us-en/astra/get-started/intro.html["Astra Control Service のマニュアル"^]
* https://docs.netapp.com/us-en/astra-control-center/index.html["Astra Control Center のドキュメント"^]
* https://docs.netapp.com/us-en/astra-data-store/index.html["Astra データストアのドキュメント"^]
* https://docs.netapp.com/us-en/astra-automation/get-started/before_get_started.html["Astra API ドキュメント"^]

