---
sidebar: sidebar 
permalink: trident-reference/tridentctl.html 
keywords: tridentctl, trident, kubernetes, commands, options, usage, flags 
summary: Trident へのシンプルなアクセスを提供するコマンドラインユーティリティである tridentctl の詳細を確認できます。 
---
= tridentctl コマンドとオプション
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
。 https://github.com/NetApp/trident/releases["Trident インストーラバンドル"^] Astra Trident へのシンプルなアクセスを提供するコマンドラインユーティリティ「 tridentctl 」が含まれています。十分な権限を持つ Kubernetes ユーザは、このロールを使用して Astra Trident をインストールしたり、 Astra Trident ポッドが含まれるネームスペースを直接管理したりできます。



== 使用可能なコマンドとオプション

使用方法については 'tridentctl --help' を実行してください

使用可能なコマンドとグローバルオプションは次のとおりです。

[listing]
----
Usage:
  tridentctl [command]
----
使用可能なコマンド：

* `create` ： Astra Trident にリソースを追加します。
* 「削除」 : Astra Trident から 1 つ以上のリソースを削除します。
* 「 GET 」： Astra Trident から 1 つ以上のリソースを取得します。
* 「 help 」：任意のコマンドに関するヘルプ。
* `imag`: Astra Trident が必要とするコンテナイメージのテーブルを印刷しなさい。
* import` ：既存のリソースを Astra Trident にインポートします。
* install` ： Astra Trident をインストールします。
* logs` ： Astra Trident からログを印刷します。
* 'send': Astra Trident からリソースを送信します
* uninstall: Astra Trident をアンインストールします。
* `update` ： Astra Trident のリソースを変更します。
* アップグレード： Astra Trident のリソースをアップグレードします。
* 've rsion ： Astra Trident のバージョンを印刷します。


フラグ：

* `-d, --debug`: デバッグ出力。
* `-h, --help` ： tridentctl のヘルプ。
* `n,--namespace string`: Astra Trident 配備の名前空間。
* `-o ,--output string`: 出力形式。JSON の 1 つ | yaml | name | wide | ps （デフォルト）。
* `s'--server string`: Astra Trident REST インタフェースのアドレス / ポート。
+

CAUTION: Trident REST インターフェイスは、 127.0.0.1 （ IPv4 の場合）または [::1] （ IPv6 の場合）のみをリスンして処理するように設定できます。




CAUTION: Trident REST インターフェイスは、 127.0.0.1 （ IPv4 の場合）または [::1] （ IPv6 の場合）のみをリスンして処理するように設定できます。



== `create`

create コマンドを実行して 'Astra Trident にリソースを追加できます

[listing]
----
Usage:
  tridentctl create [option]
----
利用可能なオプション : backend`: Astra Trident にバックエンドを追加します。



== `delete`

「削除」コマンドを実行すると、 Astra Trident から 1 つ以上のリソースを削除できます。

[listing]
----
Usage:
  tridentctl delete [option]
----
使用可能なオプション：

* backend`: Astra Trident から 1 つ以上のストレージバックエンドを削除します。
* 'Snapshot` ： Astra Trident から 1 つ以上のボリュームスナップショットを削除します。
* 'torageclas' ： Astra Trident から 1 つ以上のストレージクラスを削除します
* 'volume` ： Astra Trident から 1 つ以上のストレージボリュームを削除します




== `get`

get コマンドを実行すると 'Astra Trident から 1 つ以上のリソースを取得できます

[listing]
----
Usage:
  tridentctl get [option]
----
使用可能なオプション：

* backend`: Astra Trident から 1 つ以上のストレージバックエンドを取得します。
* 'Snapshot` ： Astra Trident から 1 つ以上のスナップショットを取得します。
* 「 torageclass 」： Astra Trident から 1 つ以上のストレージクラスを取得します。
* 'volume`: Astra Trident から 1 つ以上のボリュームを取得します


`volume` フラグ：* ``-h, --help`：ボリュームのヘルプ。* `--parentOfSubordinate string`：クエリを下位のソースボリュームに制限します。* `--subordinateOf string`:クエリをボリュームの下位に制限します。



== `images`

「 images 」フラグを実行すると、 Astra Trident が必要とするコンテナイメージのテーブルを印刷できます。

[listing]
----
Usage:
  tridentctl images [flags]
----
flags:*`-h, --help`: イメージのヘルプ。*`-v ,--k8s-version string`: Kubernetes クラスタのセマンティックバージョン。



== `import volume`

import volume コマンドを実行して、既存のボリュームを Astra Trident にインポートできます。

[listing]
----
Usage:
  tridentctl import volume <backendName> <volumeName> [flags]
----
エイリアス : volume 'v

フラグ：

* `-f ,--filename string`: YAML または JSON PVC ファイルへのパス。
* `-h, --help` ：ボリュームのヘルプ。
* ``-- 管理なし `: PV/PVC のみを作成しますボリュームのライフサイクル管理を想定しないでください。




== `install`

"install" フラグを実行して、 Astra Trident をインストールできます。

[listing]
----
Usage:
  tridentctl install [flags]
----
フラグ：

* `--autosupport-image string`：AutoSupportテレメトリ用のコンテナイメージ（デフォルトは「NetApp/Trident autosupport：<current-version>」）。
* `--autosupport-proxy string`：AutoSupport テレメトリを送信するプロキシのアドレス/ポート。
* `--enable-node-prep`：ノードに必要なパッケージをインストールします。
* `--generate-custom-yaml`:インストールを行わずにYAMLファイルを生成します。
* `-h, --help`:インストールのヘルプ。
* `--http-request-timeout`：TridentコントローラのREST APIのHTTP要求タイムアウトを上書きします（デフォルトは1m30秒）。
* `--image-registry string`:内部イメージレジストリのアドレス/ポート。
* `--k8s-timeout duration`：すべてのKubernetes処理のタイムアウト（デフォルトは3分0）。
* `--kubelet-dir string`: kubeletの内部状態のホストの場所(デフォルトは/var/lib/kubelet )
* `--log-format string`: Astra Tridentのログ形式(テキスト、JSON](デフォルトは「text」)。
* `--pv string`: Astra Tridentが使用するレガシーPVの名前は、存在しないことを確認します(デフォルトは"trident")。
* `--pvc string`：Astra Tridentで使用されている従来のPVCの名前。このPVCが存在しないことを確認します（デフォルトは「trident」）。
* `--silence-autosupport`：AutoSupport バンドルを自動的にネットアップに送信しない（デフォルトはtrue）。
* `--silent`:インストール中は、ほとんどの出力を無効にします。
* `--trident-image string`：インストールするAstra Tridentのイメージ
* `--use-custom-yaml`: setupディレクトリに存在する既存のYAMLファイルを使用します。
* `--use-ipv6`：Astra Tridentの通信にIPv6を使用




== `logs`

"logs" フラグを実行して、 Astra Trident からログを印刷することができます。

[listing]
----
Usage:
  tridentctl logs [flags]
----
フラグ：

* `-a, --archive: 特に指定がない限り ' すべてのログを含むサポート・アーカイブを作成します
* `-h, --help`: ログのヘルプ。
* `-l, --log string`: アストラトライデントログを表示します。trident | auto | trident-operator | all （デフォルトは「 auto 」）のいずれかです。
* `-- ノード文字列 : ノードポッドログの収集元となる Kubernetes ノード名
* `-p, --previous `: 以前のコンテナインスタンスのログが存在する場合は、そのログを取得します。
* `-- sidecars` : sidecar コンテナのログを取得します




== `send`

'end' コマンドを実行して 'Astra Trident からリソースを送信できます

[listing]
----
Usage:
  tridentctl send [option]
----
利用可能なオプション： AutoSupport ： AutoSupport アーカイブをネットアップに送信します。



== uninstall

uninstall フラグを実行して 'Astra Trident をアンインストールできます

[listing]
----
Usage:
  tridentctl uninstall [flags]
----
フラグ：* `-h, --help`:アンインストールのヘルプ。* `--silent`:アンインストール中のほとんどの出力を無効にします。



== `update`

「 update 」コマンドを実行して、 Astra Trident のリソースを変更できます。

[listing]
----
Usage:
  tridentctl update [option]
----
利用可能なオプション : backend`: Astra Trident のバックエンドを更新します。



== 「バージョン」

「 rsion 」フラグを実行して、「 tridentctl 」のバージョンと Trident サービスを実行して印刷できます。

[listing]
----
Usage:
  tridentctl version [flags]
----
flags:*`--client`: クライアントバージョンのみ ( サーバは不要 )*`-h, --help`: バージョンのヘルプ。
