---
sidebar: sidebar 
permalink: trident-reference/tridentctl.html 
keywords: tridentctl, trident, kubernetes, commands, options, usage, flags 
summary: Trident へのシンプルなアクセスを提供するコマンドラインユーティリティである tridentctl の詳細を確認できます。 
---
= Tridentctlを使用したAstra Tridentの管理
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
。 https://github.com/NetApp/trident/releases["Trident インストーラバンドル"^] には、 `tridentctl` Astra Tridentへのシンプルなアクセスを提供するコマンドラインユーティリティ。十分な権限を持つKubernetesユーザは、この権限を使用してAstra Tridentをインストールしたり、Astra Tridentポッドを含むネームスペースを管理したりできます。



== コマンドとグローバルフラグ

走れ `tridentctl help` 使用可能なコマンドのリストを取得するには `tridentctl` または、 `--help` 特定のコマンドのオプションとフラグのリストを取得するには、任意のコマンドにフラグを付けます。

使用方法::


[listing]
----
tridentctl [command] [--optional-flag]
----
Astra Trident `tridentctl` ユーティリティは、次のコマンドとグローバルフラグをサポートしています。

.コマンド
[%collapsible]
====
`create`:: Astra Tridentにリソースを追加
`delete`:: Astra Tridentから1つ以上のリソースを削除します。
`get`:: Astra Tridentから1つ以上のリソースを入手します。
`help`:: 任意のコマンドに関するヘルプ。
`images`:: Astra Tridentが必要とするコンテナイメージの表を出力します。
`import`:: 既存のリソースをAstra Tridentにインポート
`install`:: Astra Trident をインストール
`logs`:: Astra Tridentからログを出力
`send`:: Astra Tridentからリソースを送信
uninstall:: Astra Tridentをアンインストールします。
`update`:: Astra Tridentでリソースを変更
`update backend state`:: バックエンド処理を一時的に中断します。
`upgrade`:: Astra Tridentでリソースをアップグレード
「バージョン」:: Astra Tridentのバージョンを出力します。


====
.グローバルフラグ
[%collapsible]
====
`-d`、 `--debug`:: デバッグ出力。
`-h`、 `--help`:: ヘルプ `tridentctl`。
`-n`、 `--namespace string`:: Astra Trident導入のネームスペース。
`-o`、 `--output string`:: 出力形式。JSON の 1 つ | yaml | name | wide | ps （デフォルト）。
`-s`、 `--server string`:: Astra Trident RESTインターフェイスのアドレス/ポート。
+
--

WARNING: Trident REST インターフェイスは、 127.0.0.1 （ IPv4 の場合）または [::1] （ IPv6 の場合）のみをリスンして処理するように設定できます。

--


====


== コマンドオプションとフラグ



=== `create`

を使用します `create` Astra Tridentにリソースを追加するコマンド。

使用方法::


[listing]
----
tridentctl create [option]
----
オプション（ Options ）:: Astra Tridentにバックエンドを追加




=== `delete`

を使用します `delete` コマンドを使用して、Astra Tridentから1つ以上のリソースを削除します。

使用方法::


[listing]
----
tridentctl delete [option]
----
オプション（ Options ）:: Astra Tridentから1つ以上のストレージバックエンドを削除します。
`snapshot`:: Astra Tridentから1つ以上のボリュームSnapshotを削除します。
`storageclass`:: Astra Tridentから1つ以上のストレージクラスを削除します。
`volume`:: Astra Tridentから1つ以上のストレージボリュームを削除します。




=== `get`

を使用します `get` Astra Tridentから1つ以上のリソースを取得するためのコマンドです。

使用方法::


[listing]
----
tridentctl get [option]
----
オプション（ Options ）:: Astra Tridentから1つ以上のストレージバックエンドを取得します。
`snapshot`:: Astra Tridentから1つ以上のSnapshotを取得します。
`storageclass`:: Astra Tridentから1つ以上のストレージクラスを取得します。
`volume`:: Astra Tridentから1つ以上のボリュームを取得します。
フラグ:: ボリュームのヘルプ。
`--parentOfSubordinate string`:: クエリを下位のソースボリュームに制限します。
`--subordinateOf string`:: クエリをボリュームの下位に制限します。




=== `images`

使用 `images` Astra Tridentが必要とするコンテナイメージの表を出力するためのフラグ。

使用方法::


[listing]
----
tridentctl images [flags]
----
フラグ:: 画像のヘルプ。
`-v`、 `--k8s-version string`:: Kubernetesクラスタのセマンティックバージョン。




=== `import volume`

を使用します `import volume` コマンドを使用して、既存のボリュームをAstra Tridentにインポートします。

使用方法::


[listing]
----
tridentctl import volume <backendName> <volumeName> [flags]
----
エイリアス:: `volume, v`
フラグ:: YAMLまたはJSON PVCファイルへのパス。
`-h`、 `--help`:: ボリュームのヘルプ。
`--no-manage`:: PV/PVCのみを作成します。ボリュームのライフサイクル管理を想定しないでください。




=== `install`

を使用します `install` Astra Tridentのインストールにフラグを付けます。

使用方法::


[listing]
----
tridentctl install [flags]
----
フラグ:: AutoSupportテレメトリ用のコンテナイメージ（デフォルトは「NetApp/Trident autosupport：<current-version>」）。
`--autosupport-proxy string`:: AutoSupportテレメトリを送信するためのプロキシのアドレス/ポート。
`--enable-node-prep`:: 必要なパッケージをノードにインストールしてみます。
`--generate-custom-yaml`:: 何もインストールせずにYAMLファイルを生成します。
`-h`、 `--help`:: インストールのヘルプ。
`--http-request-timeout`:: TridentコントローラのREST APIのHTTP要求タイムアウトを上書きします（デフォルトは1m30秒）。
`--image-registry string`:: 内部イメージレジストリのアドレス/ポート。
`--k8s-timeout duration`:: Kubernetesのすべての処理のタイムアウト（デフォルトは3m0）。
`--kubelet-dir string`:: kubeletの内部状態のホストの場所(デフォルトは/var/lib/kubelet )。
`--log-format string`:: Astra Tridentのログ形式（テキスト、JSON）（デフォルトは「text」）。
`--pv string`:: Astra Tridentで使用されている従来のPVの名前から、この名前が存在しないことを確認します（デフォルトは「Trident」）。
`--pvc string`:: Astra Tridentで使用されている従来のPVCの名前から、このPVCが存在しないようにします（デフォルトは「Trident」）。
`--silence-autosupport`:: AutoSupportバンドルをNetAppに自動的に送信しない（デフォルトはtrue）。
`--silent`:: インストール中にMOST出力を無効にします。
`--trident-image string`:: インストールするAstra Tridentイメージ。
`--use-custom-yaml`:: セットアップディレクトリに存在する既存のYAMLファイルを使用します。
`--use-ipv6`:: Astra Tridentの通信にIPv6を使用




=== `logs`

使用 `logs` Astra Tridentからログを印刷するためのフラグ。

使用方法::


[listing]
----
tridentctl logs [flags]
----
フラグ:: 特に指定がないかぎり、すべてのログを含むサポートアーカイブを作成します。
`-h`、 `--help`:: ログのヘルプ。
`-l`、 `--log string`:: 表示するAstra Tridentのログ。trident | auto | trident-operator | all （デフォルトは「 auto 」）のいずれかです。
`--node string`:: ノードポッドログの収集元となるKubernetesノードの名前。
`-p`、 `--previous`:: 以前のコンテナインスタンスが存在する場合は、そのインスタンスのログを取得します。
`--sidecars`:: サイドカーコンテナのログを取得します。




=== `send`

を使用します `send` Astra Tridentからリソースを送信するコマンド。

使用方法::


[listing]
----
tridentctl send [option]
----
オプション（ Options ）:: AutoSupportアーカイブをNetAppに送信します。




=== uninstall

使用 `uninstall` Astra Tridentをアンインストールするためのフラグ。

使用方法::


[listing]
----
tridentctl uninstall [flags]
----
フラグ:: アンインストールのヘルプ。
`--silent`:: アンインストール中のほとんどの出力を無効にします。




=== `update`

を使用します `update` Astra Tridentでリソースを変更するコマンド。

使用方法::


[listing]
----
tridentctl update [option]
----
オプション（ Options ）:: Astra Tridentでバックエンドを更新




=== `update backend state`

を使用します `update backend state` バックエンド処理を一時停止または再開するコマンド。

使用方法::


[listing]
----
tridentctl update backend state <backend-name> [flag]
----
フラグ:: をに設定します `suspended` バックエンド処理を一時停止します。をに設定します `normal` バックエンド処理を再開します。に設定すると `suspended`：
+
--
* `AddVolume`、 `CloneVolume`、 `Import Volume`、 `ResizeVolume` は一時停止しています。
* `PublishVolume`、 `UnPublishVolume`、 `CreateSnapshot`、 `GetSnapshot`、 `RestoreSnapshot`、 `DeleteSnapshot`、 `RemoveVolume`、 `GetVolumeExternal`、 `ReconcileNodeAccess` 引き続き使用できます。


--
`-h`、 `--help`:: バックエンド状態のヘルプ。




=== 「バージョン」

使用 `version` のバージョンを印刷するためのフラグ `tridentctl` 実行中のTridentサービス

使用方法::


[listing]
----
tridentctl version [flags]
----
フラグ:: クライアントバージョンのみ（サーバは必要ありません）。
`-h, --help`:: バージョンのヘルプ。

